// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDG0rTZSb5CCyduLn7lFy9ihfSB0IJenf0',
    appId: '1:930080939536:web:3de6ee5d09fdfbc9233495',
    messagingSenderId: '930080939536',
    projectId: 'android-e2117',
    authDomain: 'android-e2117.firebaseapp.com',
    storageBucket: 'android-e2117.appspot.com',
    measurementId: 'G-VKEF6SD4MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkbUqYfIdxbiQPuQG85HP1maM4FCowF8',
    appId: '1:930080939536:android:68d56541f50f9597233495',
    messagingSenderId: '930080939536',
    projectId: 'android-e2117',
    storageBucket: 'android-e2117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByFGex_PpupT_3Vk5PJclUXotYOdpgTyA',
    appId: '1:930080939536:ios:6d2db95db5cfc82a233495',
    messagingSenderId: '930080939536',
    projectId: 'android-e2117',
    storageBucket: 'android-e2117.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByFGex_PpupT_3Vk5PJclUXotYOdpgTyA',
    appId: '1:930080939536:ios:14c8340e0d8013a3233495',
    messagingSenderId: '930080939536',
    projectId: 'android-e2117',
    storageBucket: 'android-e2117.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
